---
title: "Lupine volatiles"
author: "Jacob Heiling, John Powers"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE 
editor_options: 
  chunk_output_type: console
---

```{=html}
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>
```
```{r setup, include=FALSE}
library(reshape2)
library(tidyverse)
#remotes::install_github("jmpowers/bouquet", build_vignettes = T)
library(bouquet)
library(vegan)
library(ggvegan)
library(pheatmap)
library(viridis)
library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning=F, message=F, 
                      fig.path = "plots/", dev="svglite", dev.args=list(fix_text_size=FALSE), fig.height=10, fig.width=10)
```

# Read scent data

```{r read_scents}
#reading in the Shimadzu search output is slow, skip it
#source("../read_shimadzu.R")
#setwd("../Maxfield/data")
#datafiles <- list.files(pattern="Lupinus"); datafiles %>% set_names() %>% map(read.shimadzu) %>% bind_rows(.id="batch")
# lup.data <-  read.shimadzu("Lupinus_2017thru2021.txt") 
# setwd(path)
# save(lup.data, file="data/lupinus_gc_2017thru2021.rda")

load("data/lupinus_gc_2017thru2021.rda")
sort(unique(lup.data$Filename))
lup.all <- lup.data %>% 
  #filter(str_detect(Filename, "Lupinus|Blank")) %>% 
  dcast(Filename~Name, sum, value.var="Area")
rownames(lup.all) <- lup.all[,1]
lup.all[,1] <- NULL
lup.cut <- lup.all[,colSums(lup.all)>1e8]#arbitrary cutoff 5e7
```

```{r kmeans}
k <- 7
set.seed(1)
km <- kmeans(decostand(lup.cut, method="log"), k, nstart=3)

lup.km <- tibble(FileName=rownames(lup.all)) %>% 
  mutate(rowSum = rowSums(lup.all),
         Type =  str_detect(FileName, "Blank") %>% if_else("blank","sample") %>% factor,
         #str_extract(FileName, "Blank|Lupinus") %>% fct_recode(blank="Blank",sample="Lupinus")
         nameBlank = Type=="blank",
         runYear = str_extract(FileName, "2017|2018|2019|2020|2021") %>%factor,#replace_na("2018") %>%
         Cluster = km$cluster) %>% # Figure out which k-means clusters are the blanks
  mutate(kBlank = Cluster %in% (count(., nameBlank, Cluster) %>% filter(nameBlank, n>2) %>% pull(Cluster)),
         Mixup = nameBlank != kBlank)

lup.km %>% count(kBlank, nameBlank)
#Blanks are in two clusters near other samples, so kmeans not working very well to distinguish them (unless high n)
```

#  Read metadata

```{r metadata}
# Moved this section from markes_sequence.R, code above that section outputs this Rdata:
load("data/markes_sequence.rda")#../Inventory/

lupinus <- sequ.summary$FileName %in% lup.km$FileName # #str_detect(sequ.summary$FullName, "Lupinus|lupinus|Lupine")
lupinus.batchids <- sequ.summary %>% filter(lupinus) %>% select(id) %>% unique() %>% na.omit() 
lupgc <- sequ.summary %>% 
  filter(id %in% lupinus.batchids$id | lupinus) %>% #get entire batch if it had a sample that matches 
  left_join(lup.km %>% select(FileName, rowSum, nameBlank, Mixup, kBlank, Cluster), by="FileName") %>% 
  write_csv("output/lupinus_all_2017thru2021.csv")


popnames = c(brc="Brush Creek Trailhead",
             lerb="East River Bridge", erb="East River Bridge", #merge ERB + Lower ERB
             gth="Gothic Parking Lot", bur="Burro Park",
             eml="Emerald Lake", mar="Marmot Mesa",
             bvb="Bellview Bench", BellN="Bellview Bench", #N/S = north + south draws above the bench
             mex="Mexican Cut Turnoff",  elk="Elko", `401`="401", 
             npb="North Pole Basin", chs="Currant Hill", 
             bcn="Bellview Corner", bwb="Bellview Wilderness Boundary",
             ypo="Yule Pass Trailhead", cmn="Cinnamon")
# 2018 samples are all labeled BellN. 

# Get metadata from filenames in "RMBL GC-MS Data Inventory"
lupmeta <- read_tsv("data/RMBL GC-MS Data Inventory - maxfield_all210827annot.tsv", na="NA") %>% 
  filter(user=="J Heiling : Lupinus") %>% 
  distinct(FileName, .keep_all = TRUE) %>% 
  mutate(sample = na_if(sample,"") %>% coalesce(FileName) %>% str_remove(".qgd")) %>% 
  select(index, FileName, batch, sample) %>% 
  mutate(type = ifelse(str_detect(sample,"air"), "ambient", "floral"),
         sample_grid = str_remove(sample, "air_"), scented=NA_character_) %>% 
  separate(sample_grid, into=c("species","pop","sample_year","plant","rundate","GCn"), remove=F) %>% 
  full_join(lupgc %>% distinct(FileName, .keep_all = T), by="FileName") %>% 
  # lupmeta %>% select(index, FileName, sample, rowSum, Cluster, type, pop, sample_year, plant, rundate, GCn) %>% 
  #   drop_na(Cluster) %>% 
  #   separate(FileName, into=paste0("fn",1:8), remove=F, fill="right") %>% 
  #   write_csv("output/lupmeta.csv", na="") #fill in metadata for old samples (2017-2019)
  rows_update(read_tsv("data/lupmeta2017thru2021 - lupmeta.tsv", col_types="ccccccccccccccccccc") %>% 
                filter(is.na(index)) %>% 
                select(FileName, type, pop, sample_year, plant, scented, rundate), by="FileName") %>% 
  mutate(index = coalesce(index, 10000 + 1:nrow(.)),
         sample = coalesce(sample, FileName) %>% str_remove(".qgd")) %>% #these filled samples were excluded above with na_if(sample,"")
  drop_na(nameBlank) %>% #drops rows in same batchids but not integrated (other people's samples)
  filter(!nameBlank) %>% #!kBlank
  filter(type %in% c("ambient","floral")) %>% #exclude leaf controls and insects
  mutate(population = factor(recode(pop, !!!popnames), levels=unique(popnames)))

with(lupmeta, table(population, sample_year))
with(lupmeta, table(population, scented))

lup <- lup.all[lupmeta$FileName,]
rownames(lup) <- rownames(lupmeta) <- lupmeta$index
save(lup, lupmeta, file="output/lupinus_volatiles_2017thru2021.rda")
```

# Compare all samples and blanks 

```{r blanks}
lup.nmds <- metaMDS(sqrt(lup.cut), dist="bray", autotransform = FALSE, trace=F)
lup.nmds.points <- fortify(lup.nmds) %>% as_tibble() %>% 
  filter(Score=="sites") %>% left_join(lup.km, by=c("Label"="FileName"))

nmds.plot <- ggplot(lup.nmds.points, aes(x=NMDS1, y=NMDS2, shape=Type)) + theme_classic()
nmds.plot + geom_point(aes(color=log(rowSum)), size=2) + scale_color_viridis_c()
nmds.plot + geom_point(aes(color=runYear), size=2)
nmds.plot + geom_point(aes(color=factor(Cluster)), size=2)
nmds.plot + geom_point(aes(color=nameBlank), size=2)

lup.cap <- capscale(lup.cut ~ nameBlank, distance="bray", metaMDSdist = F, data=lup.km)
anova(lup.cap)
lup.cap.points <-  fortify(lup.cap) %>% as_tibble() %>% 
  filter(Score=="sites") %>% left_join(lup.km, by=c("Label"="FileName"))
ggplot(lup.cap.points, aes(x=CAP1, y=MDS1, alpha=nameBlank)) + geom_point() +
  scale_alpha_manual(values=c(0.2,1))
cap.chems <- fortify(lup.cap) %>% as_tibble() %>% filter(Score=="species") %>% arrange(desc(CAP1))
```

# Compare flowers and ambient controls

```{r ambients}
with(lupmeta, table(type, sample_year))

lup.nmds.noblanks <- metaMDS(lup[,colSums(lup)>1e8], distance="bray", autotransform=F, trace=F)
lup.nmds.points <-  as_tibble(fortify(lup.nmds.noblanks))
lup.nmds.points %>% filter(Score=="sites")%>% bind_cols(lupmeta) %>% 
ggplot(aes(x=NMDS1, y=NMDS2)) + 
  geom_label(aes(label=sample, color=type)) +
  geom_text(data= lup.nmds.points %>% filter(Score=="species"), aes(label=Label))

lup.cap.noblanks <- capscale(lup[,colSums(lup)>1e8] ~ type, distance="bray", metaMDSdist = F, data=lupmeta)
anova(lup.cap.noblanks, by="term")
lup.cap.points <-  as_tibble(fortify(lup.cap.noblanks))
lup.cap.points %>% filter(Score=="sites")%>% bind_cols(lupmeta) %>% 
  ggplot(aes(x=CAP1, y=MDS1)) + 
  geom_label(aes(label=sample, color=paste(type, sample_year))) +
  geom_text(data= lup.cap.points %>% filter(Score=="species"), aes(label=Label))
```

# Filtering

```{r filtering}
lup.data.cut <- lup.data[lup.data$Filename %in% lupmeta$FileName,]
lup.data.cut$Filename <- lupmeta$sample[match(lup.data.cut$Filename, lupmeta$FileName)]
lup.data.cut <- lup.data.cut[lup.data.cut$Name != "", ]
lup.data.cut$Name <- droplevels(lup.data.cut$Name)
longdata <- load_longdata(lup.data.cut, sample="Filename", RT="Ret.Time", name="Name", area="Area", match = "SI", maxmatch=100)
metadata <- load_metadata(lupmeta, sample="sample", type="type")
metadata$type <- factor(metadata$type)
vol.all <- make_sampletable(longdata, metadata)
chems <- make_chemtable(longdata, metadata)

### Flower filtering
chemsf <- chems %>%
  filter_RT(2, 17) %>% 
  filter_match(0.8) %>% 
  filter_freq(0.1, group = FALSE) %>% 
  filter_contaminant(cont.list = c("Decanoic acid, silver(1+) salt",
                                   "1,1,1,3,5,7,9,11,11,11-Decamethyl-5-(trimethylsiloxy)hexasiloxane",
                                   "Oxirane, decyl-","Tetradecane, 4-methyl-", "Octadecane, 1-chloro-",
                                   "Cyclobutane, 1,2-bis(1-methylethenyl)-, trans-", 
                                   "Hexyl chloroformate", "Trifluoroacetic acid,n-tridecyl ester",
                                   "Hexadecane, 2,6,11,15-tetramethyl-","Decane, 2,3,5,8-tetramethyl-",
                                   "2-Pentanol, 3-chloro-4-methyl-, (R*,R*)-(.+/-.)-")) %>% 
  filter_area(min_maximum = 1e6) %>% 
  filter_ambient_ratio(vol.all, metadata, ratio = 4) %>%
  filter_ambient_ttest(vol.all, metadata, alpha = 0.05, adjust = "fdr") %>%
  combine_filters() 
chemsf$filter_final <- with(chemsf, filter_RT == "OK" & filter_match=="OK" & filter_freq.floral == "OK" & 
                              filter_contaminant == "OK" & filter_area == "OK" & filter_ambient_ratio == "OK")

plot_filters(chemsf, option="prop")
plot_filters(chemsf, option="rarity")
plot_filters(chemsf, option="ambient")
plot_filters(chemsf, option="volcano")

#Pruning 
vol <- prune_sampletable(vol.all, chemsf, metadata)
meta <- metadata[metadata$type == "floral",][rowSums(vol)>0,]
vol <- vol[rowSums(vol)>0,]
chm <- chemsf[match(colnames(vol), chemsf$name),]

save(vol, meta, chm, file="output/lupinus_filtered_2017thru2021.rda")
write_csv(vol, "output/lupinus_vol.csv")
write_csv(meta, "output/lupinus_meta.csv")
write_csv(chm, "output/lupinus_chm.csv")
```

# Heatmap

```{r heatmap,  dev="png", dev.args=list(), fig.width=19}
pheatmap(t(vol^(1/4)), color = mako(512),
         annotation_col = select(meta, sample_year, population, sample) %>% 
           column_to_rownames("sample") %>% mutate(sample_year=factor(sample_year)))
```

# NMDS of filtered volatiles

```{r nmds_filtered}
lup.nmds <- metaMDS(sqrt(vol), dist="bray", autotransform = FALSE, trace=F)
lup.nmds.points <-  fortify(lup.nmds) %>% as_tibble()
lup.nmds.samples <- lup.nmds.points %>% filter(Score=="sites") %>% bind_cols(meta)
lup.nmds.chems <- lup.nmds.points %>% filter(Score=="species")

nmds.plot <- ggplot(lup.nmds.samples, aes(x=NMDS1, y=NMDS2)) + 
  geom_text(data=lup.nmds.chems, aes(label=Label, alpha=chm$freq.floral)) + theme_classic()

nmds.plot + geom_label(aes(label=paste0(pop, plant), color=pop)) + guides(color="none")
nmds.plot + geom_point(aes(color=sqrt(rowSums(vol)), shape=sample_year), size=2) + scale_color_viridis_c("Sqrt total peak area", option="magma") 
nmds.plot + geom_point(aes(color=sample_year), size=2)
```

# Total volatiles by run date

```{r rundate}
ggplot(meta, aes(x=paste0("20", sample_year, " run ", rundate), color=sample_year, y=rowSums(vol))) + 
  geom_violin(scale="width", draw_quantiles=(1:3)/4) + geom_point() +
  theme(axis.text.x = element_text(angle=90))
```

# CAP by GC run year

Only look at 2019 vs. 2020 here
```{r cap_year}
twoyears <- meta$sample_year %in% c("19","20")
lup.cap <- capscale(sqrt(vol[twoyears,]) ~ sample_year, dist="bray", data=meta[twoyears,])
#View(lup.cap$CCA$v)
lup.cap.points <-  fortify(lup.cap) %>% as_tibble()
lup.cap.samples <- lup.cap.points %>% filter(Score=="sites") %>% bind_cols(meta[twoyears,])
lup.cap.chems <- lup.cap.points %>% filter(Score=="species")
ggplot(lup.cap.samples, aes(x=CAP1, y=MDS1)) + 
  geom_point(aes(color=sample_year)) + 
  geom_text(data=lup.cap.chems, aes(label=Label, alpha=chm$freq.floral)) + theme_classic()
```

# PERMANOVA of populations

```{r permanova_pop}
adonis2(sqrt(vol) ~ sample_year + population, data=meta)
```

# CAP of populations

```{r cap_pop}
lup.cap <- capscale(sqrt(vol) ~ sample_year + population, dist="bray", data=meta)
lup.cap
anova(lup.cap, by="margin")
lup.cap.points <-  fortify(lup.cap) %>% as_tibble()
lup.cap.samples <- lup.cap.points %>% filter(Score=="sites") %>% bind_cols(meta)
lup.cap.chems <- lup.cap.points %>% filter(Score=="species")

ggplot(lup.cap.samples, aes(x=CAP1, y=CAP2)) + 
  geom_text(data=lup.cap.chems, aes(label=Label, alpha=chm$freq.floral)) +
  geom_label(aes(label=paste0(pop, plant), color=sample_year)) + theme_classic()

ggplot(lup.cap.samples, aes(x=CAP1, y=CAP2)) + 
  geom_point(aes(color=rowSum)) + scale_color_viridis_c("Total peak area") + theme_classic()
```

# Boxplot of populations

Compounds are in order of mean peak area, arranged in columns.

```{r boxplot, fig.width=16}
topamounts <- sort(colSums(vol), decreasing = T)
topchems <- head(names(topamounts), 18)

ggplot(enframe(topamounts) %>% mutate(name=fct_reorder(name, value)), aes(y=name, x=value)) + geom_col()

vol %>% select(topchems) %>% rownames_to_column("sample") %>% 
  pivot_longer(topchems) %>% mutate(name=fct_relevel(name, topchems)) %>% 
  left_join(meta) %>% 
  ggplot(aes(x=population, y=value, color=sample_year)) + facet_wrap(vars(name), ncol=3, scales="free_y", dir="v")+
  scale_y_sqrt() + scale_x_discrete(guide=guide_axis(angle=90))+
  geom_boxplot(position=position_dodge(width=0.9), outlier.shape = NA) + 
  geom_point(position=position_dodge(width=0.9)) +
  labs(x="Population", y="Peak area", color="Year")
```


# CAP of un/scented
```{r cap_scented}
meta.scented <- drop_na(meta, scented) #only have scores in 2019 so far
vol.scented <- vol[!is.na(meta$scented),]
lup.cap <- capscale(sqrt(vol.scented) ~ scented, dist="bray", data=meta.scented)
lup.cap
anova(lup.cap, by="margin")
lup.cap.points <-  fortify(lup.cap) %>% as_tibble()
lup.cap.samples <- lup.cap.points %>% filter(Score=="sites") %>% bind_cols(meta.scented)
lup.cap.chems <- lup.cap.points %>% filter(Score=="species")

ggplot(lup.cap.samples, aes(x=CAP1, y=MDS2)) + 
  geom_text(aes(label=paste0(pop, plant), color=scented)) +
  geom_text(data=lup.cap.chems, aes(label=Label, alpha=chm$freq.floral)) + theme_classic()

ggplot(lup.cap.samples, aes(x=CAP1, y=MDS2)) + 
  geom_point(aes(color=rowSum, shape=scented), size=3) +
  geom_text(data=lup.cap.chems, aes(label=Label, alpha=chm$freq.floral))+ scale_color_viridis_c("Total peak area") + theme_classic()
```
